---
language: python
cache: pip

env:
  matrix:
    - MOLECULE_DISTRO: debian10

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
